=== CarranzaIvan/Grupo01-TPI115-GUIA32/Ejercicio04/ejercicio-4.dtd
<!ELEMENT biblioteca (libro+, a)>
<!ELEMENT a(#PCDATA)>
<!ATTLIST a 
  href CDATA #IMPLIED
  xmlns CDATA #IMPLIED
  target (_blank|_self) "_self">
<!ELEMENT libro (titulo, autor, anio, genero*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== CarranzaIvan/Grupo01-TPI115-GUIA32/dtd_externa/ejercicio-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio-4.dtd">
<?xml-stylesheet type="text/css" href="ejercicio-4.css"?> 
<!-- ejercicio-4.xml G01 -->
<biblioteca>
    <libro>
        <titulo>El Principito</titulo>
        <autor>Antoine de Saint-Exupéry</autor>
        <anio>1943</anio>
        <genero> Literatura infantil</genero>
        <genero>Ficción especulativa</genero>
        <genero>Novela corta</genero>
        <genero>Fábula</genero>
    </libro>
    <libro>
        <titulo>Don Quijote de la Mancha</titulo>
        <autor>Miguel de Cervantes</autor>
        <anio>1605</anio>
        <genero> Ficción de aventuras</genero>
        <genero>Farsa</genero>
        <genero>Novela picaresca</genero>
        <genero>Sátira</genero>
        <genero>Novela</genero>
    </libro>
</biblioteca>
