<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="ejercicio-3.css"?> 
<!-- ejercicio-3.xml G01 -->
<!DOCTYPE integraciondegrupos [
<!ELEMENT universidad (#PCDATA)>
<!ELEMENT facultad (nombrefacultad)>
<!ELEMENT nombrefacultad (#PCDATA)>
<!ELEMENT carrera (nombrecarrera,codigocarrera)>
<!ELEMENT nombrecarrera (#PCDATA)>
<!ELEMENT codigocarrera (#PCDATA)>
<!ELEMENT materia (nombremateria,codigomateria)>
<!ELEMENT nombremateria (#PCDATA)>
<!ELEMENT codigomateria (#PCDATA)>
<!ELEMENT docente (codigod,nombred,apellidosd)>
<!ELEMENT codigod (#PCDATA)>
<!ELEMENT nombred (#PCDATA)>
<!ELEMENT apellidosd (#PCDATA)>
<!ELEMENT actividadevaluada (#PCDATA)>
<!ELEMENT integraciondegrupos (grupo+)>
<!ELEMENT grupo (descripcion,tema,alumno)>
<!ATTLIST grupo numero ID #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tema (#PCDATA)>
<!ELEMENT grupo (alumnos+)>
<!ELEMENT alumno (carnet,nombre,apellido,genero,calificacion?)>
<!ATTLIST alumno codigo ID #REQUIRED>
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ATTLIST genero sexo (F|M) "F">
<!ELEMENT calificacion (#PCDATA)>
]>
<integraciondegrupos>
<universidad>UNIVERSIDAD DE EL SALVADOR</universidad>
<facultad>
<nombrefacultad>Ingenieria y Arquitectura</nombrefacultad>
</facultad>
<carrera>
<nombrecarrera>ingenieria en sistemas informaticos</nombrecarrera>
<codigocarrera>i10515-1998</codigocarrera>
</carrera>
<materia>
<nombremateria>tecnicas de programacion para internet</nombremateria>
<codigomateria>tpi115</codigomateria>
</materia>
<docente>
<codigod>Docente: BO3</codigod>
<nombred>Carlos </nombred>
<apellidosd>Balmore Ortiz</apellidosd>
</docente>
<actividadevaluada>guia 32</actividadevaluada>
<grupo numero="uno">
<descripcion>Grupo uno</descripcion>
<tema>Extensible Markup Language XML (Lenguaje de Marcado Extensible)</tema>
<alumno codigo="LC18025">
<carnet>LC18025</carnet>
<nombre>Aura Guadalupe</nombre>
<apellidos>Lopez Chavez</apellidos>
<genero sexo="f"></genero>
<!--<calificacion> </calificacion>-->
</alumno>
<alumno codigo="CS21024">
<carnet>CS21024</carnet>
<nombre>Ivan Alexander</nombre>
<apellidos>Carranza Sanchez</apellidos>
<genero sexo="m"></genero>
<calificacion>Calificacion 8</calificacion>
</alumno>
<alumno codigo="AL17015">
<carnet>AL17015</carnet>
<nombre>Monica  Anabel</nombre>
<apellidos>Anaya Lopez</apellidos>
<genero sexo="f"></genero>
<!--<calificacion> </calificacion>-->
</alumno>
<alumno codigo="MP17016">
<carnet>MP17016</carnet>
<nombre>Luis Carlos</nombre>
<apellidos>Morales Perez</apellidos>
<genero sexo="m"></genero>
<calificacion>Calificacion 7</calificacion>
</alumno>
</grupo>
<grupo numero="dos">
<descripcion>Grupo dos</descripcion>
<tema> HTML (Lenguaje de Marcado Extensible)</tema>
<alumno codigo="CC18026">
<carnet>CC18026</carnet>
<nombre>Juan Enrique</nombre>
<apellidos>Campos Cruz</apellidos>
<genero sexo="M"></genero>
<calificacion> Calificacion 9</calificacion>
</alumno>
<alumno codigo="MH20024">
<carnet>MH20024</carnet>
<nombre>Mateo Alexander</nombre>
<apellidos>Mendez Hernandez</apellidos>
<genero sexo="m"></genero>
<calificacion>Calificacion 7</calificacion>
</alumno>
<alumno codigo="AS16090">
<carnet>AL17015</carnet>
<nombre>Maria Elena</nombre>
<apellidos>Amaya Sanches</apellidos>
<genero sexo="f"></genero>
<!--<calificacion> </calificacion>-->
</alumno>
<alumno codigo="GL19016">
<carnet>GL19016</carnet>
<nombre>Luis Ernesto</nombre>
<apellidos>Gonzales Lopez</apellidos>
<genero sexo="m"></genero>
<calificacion>Calificacion 5</calificacion>
</alumno>
</grupo>
<a xmlns="http://www.w3.org/1999/xhtml" href="../index.html" target="_self">Inicio</a>
</integraciondegrupos>
