<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo-ii-1c.css"?>
<!-- ejemplodtd1.xml GRUPO_01 -->
<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+,a)>
<!-- Enlace de retorno-->
    <!ELEMENT a (#PCDATA)>
    <!ATTLIST a 
      href CDATA #IMPLIED
      xmlns CDATA #IMPLIED
      target (_blank|_self) "_self">

    <!-- Elementos del fichero-->
<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>		]>

<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
 </ficha>
 <a xmlns="http://www.w3.org/1999/xhtml" href="../index.html" target="_self">Inicio</a>
</fichero>

