<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="estilo-ii-1a.css"?>
<!-- ejemplodtd1.xml GRUPO_01 -->
<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+,a)>
<!-- Enlace de retorno-->
    <!ELEMENT a (#PCDATA)>
    <!ATTLIST a 
      href CDATA #IMPLIED
      xmlns CDATA #IMPLIED
      target (_blank|_self) "_self">

    <!-- Elementos del fichero-->
  <!ELEMENT ficha (nombre, apellido, estatura*, direccion*, telefono*, DUI?, ISSS?)>
		<!ELEMENT nombre (#PCDATA)>
			<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
			<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT estatura (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
		<!ELEMENT ISSS (#PCDATA)>		]>
<fichero>
  <!-- Ficha 1-->
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido> Fernandez</apellido>
  <estatura>1.7mt</estatura>
  <direccion>c/Ulises, 36</direccion>
  <telefono>2525-2525</telefono>
  <ISSS>4852256-54488-6</ISSS>
 </ficha>
  <!-- Ficha 2-->
 <ficha>
  <nombre sexo="masculino" edad="18">Romeo</nombre>
  <apellido> Santos</apellido>
  <estatura>1.8mt</estatura>
  <direccion>c/Carmen, 37</direccion>
  <ISSS>485225754-45</ISSS>
 </ficha>
 <a xmlns="http://www.w3.org/1999/xhtml" href="../index.html" target="_self">Volver</a>
</fichero>

